version: "3.8"

services:
  # dotnet core 8
  dotnetcore:
    image: dmcr.microsoft.com/devcontainers/dotnet:dev-8.0
    container_name: dotnetcore
    ports:
      - "8080:80"
    volumes:
      - ./src:/app
    working_dir: /app
    command: /bin/bash -c "dotnet restore && dotnet run"

  # ms sql server
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./mssql:/var/opt/mssql

  # redis stack
  redis:
    image: redis/redis-stack
    container_name: redis
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis-data:var/lib/redis-stack

volumes:
  redis-data:
